### ISSUE TITLE
You are using an unsupported version of Python

### ISSUE THREAD

**Issue by RoninFromMoscow** [obra/Youtube2Webpage#25]
I got `Ubuntu 18.04`

### requirements

```bash
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp  # Make executable
```

```bash
sudo apt install ffmpeg
```

### installation

```bash
mkdir test-project
cd test-project
git clone https://github.com/obra/Youtube2Webpage.git
cd Youtube2Webpage
```

### first run

```bash
./yt-to-webpage.pl project-name "https://www.youtube.com/watch?v=jNQXAC9IVRw"

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
Can't open '<undef>' for reading: 'No such file or directory' at ./yt-to-webpage.pl line 21
```

in error `versions 3.8 and above` but I got `python` is `2.7*` and `python3` is `3.11`, but which is used?

### fixed python version

```bash
sudo apt install python3.8
```
updated `~/.bashrc`
```
alias python='/usr/bin/python3.8'
alias python3='/usr/bin/python3.8'
```
then
```bash
source ~/.bashrc
```
and now
```bash
python --version
Python 3.8.0
python3 --version
Python 3.8.0
```
ok, again
```bash
./yt-to-webpage.pl project-name "https://www.youtube.com/watch?v=jNQXAC9IVRw"

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
Can't open '<undef>' for reading: 'No such file or directory' at ./yt-to-webpage.pl line 21
```

Please help me to understand how should it work?

**Comment by obra** [comment]
You're seeing an issue with your install of yt-dlp, not this project. I'd suggest you report this to them.

On Mon, Jan 8, 2024, at 2:58 PM, RoninFromMoscow wrote:
> 
> 
> I got `Ubuntu 18.04`
> 
> requirements
> 
> sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
> sudo chmod a+rx /usr/local/bin/yt-dlp  # Make executable
> sudo apt install ffmpeg
> installation
> 
> mkdir test-project
> cd test project
> git clone https://github.com/obra/Youtube2Webpage.git
> cd Youtube2Webpage
> first run
> 
> ./yt-to-webpage.pl project-name "https://www.youtube.com/watch?v=jNQXAC9IVRw"
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
>   File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
> ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
> Can't open '<undef>' for reading: 'No such file or directory' at ./yt-to-webpage.pl line 21
> in error `versions 3.8 and above` but I got `python` is `2.7*` and `python3` is `3.11`, but which is used?
> 
> fixed python version
> 
> sudo apt install python3.8
> updated `~/.bashrc`
> 
> `alias python='/usr/bin/python3.8'
> alias python3='/usr/bin/python3.8'
`

**Comment by RoninFromMoscow** [comment]
ok, but what version of `yt-dlp` is used for `Youtube2Webpage` project to work correctly? .. and ffmpeg by the way?

**Comment by obra** [comment]
We don't have a specific requirements. Anything recentish should be fine
